version: "3.8"

services:
  mysql-server:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: candidate
      MYSQL_USER: ogleh
      MYSQL_PASSWORD: 12345
